### ISSUE TITLE
Regarding installation of Mobile-Live-Chat-Support-Server

### ISSUE THREAD

**Issue by khemitverma** [fabioberger/Mobile-Live-Chat-Support-Server#1]
Hello,
I am installing  the "Mobile-Live-Chat-Support-Server".I follow the step of installation.But when i run "node server" command from command prompt i got the error:

Error: Cannot find module 'node-xmpp'
    at Function.Module._resolveFilena
    at Function.Module._load (module.
    at Module.require (module.js:364:
    at require (module.js:380:17)
    at Object.<anonymous> (E:\chatSer
    at Module._compile (module.js:456
    at Object.Module._extensions..js
    at Module.load (module.js:356:32)
    at Function.Module._load (module.
    at Module.require (module.js:364:
    at require (module.js:380:17)

How can i resolve the issue??

**Comment by soroushjp** [comment]
@khemitverma Did you run npm install? It sounds like it is complaining that node-xmpp isn't installed

**Comment by khemitverma** [comment]
Now previous problem is solved but now i get another problem i attached 
the screenshot.Please review it

**Comment by soroushjp** [comment]
@khemitverma No screenshot is attached to the comment. You might have attached it to the email reply but it doesn't show up on GitHub.
